<script setup lang="ts">
import { Head, Link } from "@inertiajs/vue3";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import { NBreadcrumb, NBreadcrumbItem, NButton, NEmpty } from "naive-ui";

interface Props {
    id: string;
}

defineProps<Props>();
</script>

<template>
    <Head :title="id" />

    <AuthenticatedLayout>
        <div class="flex flex-row items-center">
            <div class="flex flex-row items-center space-x-2">
                <Link href="/projects">
                    <n-button size="small" tertiary>
                        <template #icon>
                            <i class="icon icon-300">chevron_left</i>
                        </template>
                    </n-button>
                </Link>
                <h1
                    class="text-2xl font-semibold text-brand dark:text-indigo-500/60"
                >
                    {{ id }}
                </h1>
                <n-divider vertical />
                <div>
                    <n-breadcrumb>
                        <n-breadcrumb-item> home </n-breadcrumb-item>
                        <n-breadcrumb-item> Projects </n-breadcrumb-item>
                        <n-breadcrumb-item> View </n-breadcrumb-item>
                    </n-breadcrumb>
                </div>
            </div>
        </div>

        <div class="mt-8">
            <header class="flex flex-row justify-between items-center">
                <h2 class="text-xl">Reports</h2>
                <div class="flex flex-row items-center space-x-2">
                    <Link :href="`/projects/${id}/flow`">
                        <n-button tertiary type="primary">
                            <template #icon>
                                <i class="icon icon-400">conversion_path</i>
                            </template>
                            Flows
                        </n-button>
                    </Link>
                    <n-button tertiary type="primary">
                        <template #icon>
                            <i class="icon icon-400">list</i>
                        </template>
                        Recon stories
                    </n-button>
                </div>
            </header>
        </div>
        <n-empty :show-icon="false">
            <div class="flex flex-col space-y-2 items-center text-center">
                <span
                    class="grid place-items-center grow-0 shrink-0 h-20 w-20 rounded-full bg-olive-100 dark:bg-dark-700"
                >
                    <i class="icon text-5xl text-olive-700">monitoring</i>
                </span>
                <h2
                    class="text-olive-1000 dark:text-olive-300 text-xl font-semibold"
                >
                    Setup reports
                </h2>
                <p class="prose w-2/3 dark:text-olive-700">
                    Custom reports ensure that you can configure the proper
                    insights that you need from the data generated by
                    reconciliation stories
                </p>
                <n-button type="primary" ghost>+ Add report</n-button>
            </div>
        </n-empty>
    </AuthenticatedLayout>
</template>

<style scoped></style>
